export const ROW_TYPE = 'row'
export const TEXT_TYPE = 'text'
export const TEXTAREA_TYPE = 'textarea'
export const TEL_TYPE = 'tel'
export const EMAIL_TYPE = 'email'
export const CHECKBOX_TYPE = 'checkbox'
export const BUTTON_TYPE = 'button'

export const BLUE_BUTTON_COLOR = 'blue'
export const WHITE_BUTTON_COLOR = 'white'